dependencies:
  - role: base
  - role: cgmemtime
  - role: tentris
  #- role: fuseki
  #- role: gstore
  #- role: virtuoso
  #- role: graphdb
  #- role: blazegraph
  #- role: triplebit
  #- role: rdf3x
