- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: tentris
  register: tempdir

#- name: Download tentris
#  get_url:
#    url: https://raw.githubusercontent.com/dice-group/iswc2020_tentris/master/binaries/tentris_{{ tentris_version }}.zip
#    dest: "{{ tempdir.path }}/tentris_{{ tentris_version }}.zip"

#- name: Unzip tentris
#  unarchive:
#    remote_src: yes
#    src: "{{ tempdir.path }}/tentris_{{ tentris_version }}.zip"
#    dest: "{{ tempdir.path }}"

- name: Create installation directory
  file:
    path: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}"
    state: directory
#
#- name: Install tentris_terminal
#  copy:
#    remote_src: yes
#    src: "{{ tempdir.path }}/tentris_terminal"
#    dest: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}/tentris_terminal"
#    mode: 0755

- name: Install tentris_server
  copy:
    remote_src: yes
    src: "/home/PhilipCoutinhoDeSousa/tentris_{{ tentris_version }}/tentris_server"
   # src: "{{ tempdir.path }}/tentris_server"
    dest: "{{ target_dir }}/triplestores/tentris/{{ tentris_version }}/tentris_server"
    mode: 0755

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
